In [2]:
import numpy as np


**Array fundamentals**

In [3]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

**Slicing and updating**

In [4]:
a[0]

np.int64(1)

In [5]:
a[0]=10

In [6]:
a

array([10,  2,  3,  4,  5])

In [7]:
a[:3]

array([10,  2,  3])

In [8]:
a[3:]

array([4, 5])

Two- and higher-dimensional arrays can be initialized from nested Python sequences:

In [9]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a[1,2]

np.int64(6)

In [11]:
a[1,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

**Array attributes**

ndim, shape, size, and dtype

In [12]:
a.ndim

2

In [13]:
a.shape

(3, 3)

In [14]:
a.size

9

In [15]:
a.dtype

dtype('int64')

**How to create a basic array**

np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [16]:
np.zeros(2)

array([0., 0.])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.empty(3)

array([1., 1., 1.])

In [19]:
np.arange(4)

array([0, 1, 2, 3])

In [20]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [26]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Specifying your data type

In [27]:
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1])

**Adding, removing, and sorting elements**

In [28]:
arr=np.array([4,5,2,1,6])
np.sort(arr)

array([1, 2, 4, 5, 6])

In [34]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [39]:
x=np.array([[1,2],[4,5]])
y=np.array([[9,10]])
z=np.concatenate((x,y))

arr.reshape()

In [46]:
a=np.array([1,2,3,4,5,6])
a.reshape(3,2)


array([[1, 2],
       [3, 4],
       [5, 6]])

**How to convert a 1D array into a 2D array (how to add a new axis to an array)**


You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

In [47]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [49]:
# Using np.newaxis will increase the dimensions of your array by one dimension when used once.
a2=a[np.newaxis,:]
a2.shape

(1, 6)

In [51]:
col_vector=a[:,np.newaxis]
col_vector.shape

(6, 1)

In [52]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

**condition based slicing**




In [53]:
a=np.array([1,2,3,4,5])

In [55]:
print(a[a>3])

[4 5]


In [58]:
print(a[a>=1])

[1 2 3 4 5]


In [59]:
print(a[a%2==0])

[2 4]


In [64]:
print(a[(a>2)&(a%2==0)])

[4]


In [66]:
five=(a>3)|(a==2)
five

array([False,  True, False,  True,  True])

In [67]:
b=np.nonzero(a<3)
print(b)


(array([0, 1]),)


How to create an array from existing data

In [68]:
a=np.array([1,2,3,4,5,6,7,8,9,9])

In [69]:
a1=a[2:5]

In [70]:
a1

array([3, 4, 5])

In [71]:
a1=np.array([[1,2,3],
             [4,5,6]])
a2=np.array([[11,12,13],
             [14,15,16]])
np.vstack((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [72]:
np.hstack((a1,a2))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

Basic array operations

In [74]:
# addition, subtraction, multiplication, division, and more

In [75]:
data=np.array([1,2])
ones=np.ones(2)
add=data+ones
add

array([2., 3.])

In [76]:
data=np.array([1,2])
ones=np.ones(2)
sub=data-ones
sub

array([0., 1.])

In [77]:
a=np.array([1,2,3,4,5])
b=a.sum()
b

np.int64(15)

Broadcasting

In [78]:
data=np.array([1,2,3,5])
data*1.5


array([1.5, 3. , 4.5, 7.5])

maximum, minimum, sum, mean, product, standard deviation, and more

In [79]:
data=np.array([1,1,2,33,4,5])
data.max()

np.int64(33)

In [80]:
data.min()

np.int64(1)

In [84]:
data.mean()

np.float64(7.666666666666667)

In [86]:
data.sum()

np.int64(46)

In [95]:
a=np.arange(1,100)
np.random.choice(a,2)

array([18, 75])

In [97]:
a=np.array([1,2,3,4,5,3,4,5,6,9])
unq=np.unique(a)
unq

array([1, 2, 3, 4, 5, 6, 9])

In [99]:
a=[1,2,3,4,5,3,333,4]
np.unique(a)

array([  1,   2,   3,   4,   5, 333])

Transposing and reshaping a matrix


In [110]:
a=np.array([[1,2,3],[4,5,6]])
a.reshape(3,2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

How to reverse an array

In [112]:
arr=[2,4,3,1,5,6,7]
np.flip(arr)

array([7, 6, 5, 1, 3, 4, 2])